#
# Module manifest for module 'Dataverse'
#
# Generated by: PowerShell Module Generator
#
# Generated on: 9/19/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Dataverse.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'b8d2f4a6-3c5e-4f1d-9a8b-7e2c1f5d3a9e'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module for interacting with Microsoft Dataverse environments. Provides comprehensive functionality for connecting to Dataverse, managing authentication, and performing CRUD operations on tables and records.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.3'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    @{ModuleName = 'Az.Accounts'; ModuleVersion = '3.0.0'}
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Connect-PSDVOrg',
    'Update-PSDVAccessToken',
    'Invoke-PSDVWebRequest',
    'Read-PSDVTableData',
    'Get-PSDVTableDetail',
    'Get-PSDVTableColumn',
    'Get-PSDVTableItem',
    'Get-PSDVTableItemAuditHistory',
    'Get-PSDVTableItemChangeHistory',
    'New-PSDVTableItem',
    'Update-PSDVTableItem',
    'Remove-PSDVTableItem'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Dataverse', 'PowerPlatform', 'CRM', 'Dynamics365', 'REST', 'API', 'Microsoft')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/microsoft/Dataverse/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoft/Dataverse'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoft/Dataverse/main/icon.png'

        # ReleaseNotes of this module
        ReleaseNotes = @'
Dataverse v1.0.0 - Initial Release

This is the initial release of the Dataverse PowerShell module providing comprehensive Microsoft Dataverse integration capabilities.

Key Features:
- Multiple authentication methods (Service Principal, Managed Identity, Interactive)
- Complete CRUD operations for Dataverse tables and records
- Advanced OData querying with filters, expansion, and field selection
- Table and column metadata operations with filtering support
- Audit history and change tracking capabilities
- Automatic token refresh and session management
- Support for large result set pagination
- PowerShell 7.3+ compatibility with Constrained Language Mode support
- PSScriptAnalyzer compliant code following best practices
- Comprehensive help documentation with examples
- Module installation and testing utilities

For detailed documentation, visit: https://github.com/microsoft/Dataverse
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/microsoft/Dataverse/blob/main/README.md'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}